watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  top-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar top"
    alignment:
      position: "bottom"
      center: false
    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        [
          "komorebi_workspaces",
          "komorebi_active_layout",
          media
        ]
      center: [
        active_window
      ]
      right:
        [
          volume,
          ubattery,
          uspace,
          uwifi,
          clock,
          power_menu
        ]
widgets:
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%I:%M}"
      label_alt: "{%A %d %B %Y}"
      timezones: []

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: " \ue654 Offline"
      label_workspace_btn: "{index}"
      label_workspace_active_btn: "{index}"
      label_workspace_populated_btn: "{index}"
      label_default_name: "{index}"
      hide_empty_workspaces: true
      hide_if_offline: false

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
        ]
      layout_icons:
        bsp: "BSP"
        columns: "COL"
        rows: "ROW"
        grid: "GRD"
        vertical_stack: "VST"
        horizontal_stack: "HST"
        ultrawide_vertical_stack: "UWS"
        right_main_vertical_stack: "RMV"
        monocle: "MON"
        maximised: "MAX"
        floating: "FLT"
        paused: "PAU"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      callbacks:
        on_left: "next_layout"
        on_middle: "toggle_monocle"
        on_right: "prev_layout"

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: "No Active Window"
      label_icon: false
      label_icon_size: 16
      max_length: 54
      max_length_ellipsis: "\u2026"
      monitor_exclusive: false
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span><img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\speed-upload.svg\"/></span> {upload_speed}"
      label_alt: "<span><img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\speed-download.svg\"/></span> {download_speed}"
      update_interval: 1000
      callbacks:
        on_left: 'toggle_label'
        on_right: 'exec cmd /c Taskmgr'
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\uf001</span> {title}"
      label_alt: "<span>\uf001</span> {title}"
      hide_empty: false
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 56
        label_alt: 56
      show_thumbnail: false
      controls_only: false
      controls_left: false
      controls_hide: true
      thumbnail_alpha: 50
      thumbnail_padding: 38
      thumbnail_corner_radius: 13
      icons:
        prev_track: "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\skip-back.svg\"/>"
        next_track: "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\skip-forward.svg\"/>"
        play: "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\play.svg\"/>"
        pause: "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\pause.svg\"/>"
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      image_icon_size: 16
      app_list:
        - {icon: "C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\folder-closed.svg", launch: "explorer"}
        - {icon: "C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\earth.svg", launch: "C:\\Program Files\\Naver\\Naver Whale\\Application\\whale.exe"}
        - {icon: "C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\code-xml.svg", launch: "code"}
        - {icon: "C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\terminal.svg", launch: "C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.21.3231.0_x64__8wekyb3d8bbwe\\WindowsTerminal.exe"}
        - {icon: "C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\notepad-text.svg", launch: "notepad"}
  app_button:
      type: "yasb.custom.CustomWidget"
      options:
        label: "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\layout-grid.svg\"/>"
        label_alt: "<span>\uf40e</span>"
        class_name: "app-button"
        callbacks:
          on_left: "exec start_menu"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp_c}"
      label_alt: '{location}: Temperature {min_temp_c} / {max_temp_c} ー Humidity {humidity}'
      api_key: '3bf4cf9a7c3f40d6b31174128242807'
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: 'VietNam,Ho Chi Minh'
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\sun.svg\"/>"
        clearNight: "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\moon.svg\"/>"
        cloudyDay: "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\cloud-sun.svg\"/>"
        cloudyNight: "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\cloud-moon.svg\"/>"
        rainyDay: "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\cloud-sun-rain.svg\"/>"
        rainyNight: "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\cloud-moon-rain.svg\"/>"
        snowyIcyDay: ""
        snowyIcyNight: ""
        blizzard: ""
        default: ""
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011 "
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<h2></h2>"
      image_path: "C:\\Users\\ngxuanchat\\Wallpapers"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 200
        image_per_page: 6
        show_buttons: false
        orientation: "portrait"
        image_spacing: 10
        lazy_load: true
        lazy_load_delay: 10
        lazy_load_fadein: 200
        image_corner_radius: 20
        enable_cache: true
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "<"
      label_expanded: ">"
      label_position: "right"
      icon_size: 14
      pin_click_modifier: "alt"
      show_unpinned: false
      show_unpinned_button: false
      show_battery: false
      show_volume: false
      show_network: false
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "{device_name}"
      label_no_device: "No devices connected"
      label_device_separator: ", "
      max_length: 10
      max_length_ellipsis: "..."
      icons: 
        bluetooth_on: "\udb80\udcaf"
        bluetooth_off: "\udb80\udcb2"
        bluetooth_connected: "\udb80\udcb1"
      device_aliases:
        - name: "T5.0"
          alias: "\uf025"
      callbacks:
        on_left: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span> {device_count}"
      label_alt: "{device_name}"
      label_no_device: "No devices connected"
      label_device_separator: ", "
      max_length: 10
      max_length_ellipsis: "..."
      icons: 
        bluetooth_on: "\udb80\udcaf"
        bluetooth_off: "\udb80\udcb2"
        bluetooth_connected: "\udb80\udcb1"
      device_aliases:
        - name: "T5.0"
          alias: "\uf025"
      callbacks:
        on_left: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  ubattery:
    type: "yasb.custom.CustomWidget"
    options:
      label: " 󰁹 100% "
      label_alt: " 󰁹 100% "
      class_name: "ubattery-widget"
  uwifi:
    type: "yasb.custom.CustomWidget"
    options:
      label: " pixel "
      label_alt: " pixel "
      class_name: "uwifi-widget"
  uwifi:
    type: "yasb.custom.CustomWidget"
    options:
      label: "  nxc "
      label_alt: "  nxc "
      class_name: "uwifi-widget"
  uspace:
    type: "yasb.custom.CustomWidget"
    options:
      label: "ㅤ‎"
      label_alt: "‎ㅤ"
      class_name: "uspace-widget"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "{level}:{volume}"
      tooltip: false
      volume_icons:
        - "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\volume-x.svg\"/>" # Icon for muted
        - "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\volume.svg\"/>" # Icon for 0-10% volume
        - "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\volume.svg\"/>" # Icon for 11-30% volume
        - "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\volume-1.svg\"/>" # Icon for 31-60% volume
        - "<img src=\"C:\\Users\\ngxuanchat\\.config\\yasb\\icons\\volume-2.svg\"/>" # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"